# Base configs
image_fulls_loc:  "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Shots by Yiran"
subtitle: "See through my eyes"
author:  "Yiran Mao"
header:
 title: "Shots"
 subtitle: "by Yiran Mao"
footer:
 name: "Hey there!"
 bio: "I’m a PhB/B.Phil student@ANU, focusing on math, computer science and physics. Star wars fan, badminton and hiking lover."
social_urls:
  instagram: "https://www.instagram.com/ravenfrank_m/"
  twitter: "https://twitter.com/YiranFrankM"

# Feed configs
plugins:
  - jekyll-feed
title: Yiran's Shots
description: Welcome to my Photo Gallery!
author: Yiran Mao
